"""Package — see module README.md."""

from fleet_server.container_templates.catalog import (
    _safe_ref_path,
    apply_requirement_template_package,
    build_cache_file,
    bundle_fingerprint,
    copy_default_templates,
    dockerfiles_allow_root,
    ensure_template_layout,
    load_build_cache,
    load_requirement_templates,
    max_template_package_upload_bytes,
    requirement_templates_file,
    save_requirement_templates,
    template_by_id,
    validate_requirement_id,
    validate_template_row,
)
from fleet_server.container_templates.build import (
    BUILTIN_CERTIFICATOR_SOURCE_INGEST_TEMPLATE_ID,
    _record_build_success,
    _stderr_suggests_missing_buildx,
    _template_build_network_allowed,
    meta_build_template_if_missing,
    parse_build_if_missing_query,
    prefetch_requirement_template_images,
    prefetch_template_images_enabled,
    resolve_cached_image,
    run_template_build,
)
from fleet_server.container_templates.api import templates_api_payload, status_api_payload, resolve_api_payload, inject_template_image_into_docker_argv

__all__ = [
    "BUILTIN_CERTIFICATOR_SOURCE_INGEST_TEMPLATE_ID",
    "requirement_templates_file",
    "build_cache_file",
    "dockerfiles_allow_root",
    "ensure_template_layout",
    "load_requirement_templates",
    "load_build_cache",
    "save_requirement_templates",
    "validate_requirement_id",
    "template_by_id",
    "bundle_fingerprint",
    "max_template_package_upload_bytes",
    "apply_requirement_template_package",
    "copy_default_templates",
    "validate_template_row",
    "_safe_ref_path",
    "_template_build_network_allowed",
    "_record_build_success",
    "prefetch_template_images_enabled",
    "prefetch_requirement_template_images",
    "parse_build_if_missing_query",
    "meta_build_template_if_missing",
    "resolve_cached_image",
    "run_template_build",
    "_stderr_suggests_missing_buildx",
    "templates_api_payload",
    "status_api_payload",
    "resolve_api_payload",
    "inject_template_image_into_docker_argv",
]
